### ISSUE TITLE
Log4j log4shell vulnerability mitigation

### ISSUE THREAD

**Issue by pa1codehub** [mhamzas/Scripted-Data-Loader-for-Mac-Unix#1]
Hi @mhamzas,
Do you have a patch version for the data loader to fix the log4J vulnerability? I tried to include the new Data Loader V53.0.3 version from https://github.com/forcedotcom/dataloader and updated the encrypt and process files but it is giving **Unable to find swt jar for linux : amd64** error.
Please let me know if you have the updated code for the new version?

**Comment by mhamzas** [comment]
Hi @pa1codehub, As Salesforce now supports mac, I wasn't managing this repo. 
But let me try updating it. Thanks !

**Comment by mhamzas** [comment]
I've updated the repo, can you please try at your end. 
NOTE: Please make sure to download all the files with latest changes.

**Comment by pa1codehub** [comment]
@mhamzas Getting the same error - Unable to find swt jar for linux : amd64.
Also, we need to update the process.sh to call the com.salesforce.dataloader.process.DataLoaderRunner instead of ProcessRunner class.  They have moved the main method to DataLoaderRunner class.

**Comment by mhamzas** [comment]
When you're getting this error?

For the Error `Unable to find swt jar for linux : amd64`, you may need to install SWT: [http://www.jcontrol.org/download/readme_eclipse_en.html](http://www.jcontrol.org/download/readme_eclipse_en.html)

Yes, you're right about the `DataLoaderRunner`, I've updated the source.

**Comment by pa1codehub** [comment]
When I am trying to run the process.sh, I'm seeing the error. The data loader team provided the SWT files for Linux, maybe I need to add the SWT to the java home. 
https://github.com/ashitsalesforce/dataloader/tree/master/local-proj-repo/local/swt

**Comment by mhamzas** [comment]
> When I am trying to run the process.sh, I'm seeing the error. The data loader team provided the SWT files for Linux, maybe I need to add the SWT to the java home. https://github.com/ashitsalesforce/dataloader/tree/master/local-proj-repo/local/swt

Can you show me the complete output?

**Comment by pa1codehub** [comment]
> > When I am trying to run the process.sh, I'm seeing the error. The data loader team provided the SWT files for Linux, maybe I need to add the SWT to the java home. https://github.com/ashitsalesforce/dataloader/tree/master/local-proj-repo/local/swt
> 
> Can you show me the complete output?

I have added the swtlinux_x86_64 folder to the same location of the dataloader-54.0.0-uber.jar. It gives the following error.

![dataloader_error](https://user-images.githubusercontent.com/22842007/151011050-bb168fb6-eed9-4c95-aff4-6be32bcb605d.png)

**Comment by pa1codehub** [comment]
Hi @mhamzas,
Seems like the latest version is looking for SWTDirectory and SWTJarPath in the DataLoaderRunner class which is throwing this error. Wondering if just importing the SWT library and updating the class path would solve this issue?

**Comment by mhamzas** [comment]
> When you're getting this error?
> 
> For the Error `Unable to find swt jar for linux : amd64`, you may need to install SWT: http://www.jcontrol.org/download/readme_eclipse_en.html
> 
> Yes, you're right about the `DataLoaderRunner`, I've updated the source.

I am trying to fix it at my end, whilst; try installing system-provided java and jni native libraries using
`apt-get install libswt-gtk-4-java libswt-cairo-gtk-4-jni`

**Comment by pa1codehub** [comment]
Hi @mhamzas ,
it is working and able to download the data from Salesforce after updating the process.sh with the following command
`java -jar dataloader-54.0.0-uber.jar run.mode=batch salesforce.config.dir=$CONF_DIR process.name=$PROCESS > /apps/sdl/data/"$1".OutPut."$now".log`

and updated `singleton="false"` to `scope="singleton"` in process-conf.xml

But the output log file is not generated if we have a file already. It is giving the below message which was not the case earlier.
`[WSC][DataLoaderRunner.main:104]Log file already exists, appending to status/sfdcSoapTrace.log`

**Comment by pa1codehub** [comment]
Hi @mhamzas,
Also, we are not using any log-conf.xml in the code right? Because I do not see any log configuration files in the project.

**Comment by mhamzas** [comment]
> Hi @mhamzas , it is working and able to download the data from Salesforce after updating the process.sh with the following command `java -jar dataloader-54.0.0-uber.jar run.mode=batch salesforce.config.dir=$CONF_DIR process.name=$PROCESS > /apps/sdl/data/"$1".OutPut."$now".log`
> 
> and updated `singleton="false"` to `scope="singleton"` in process-conf.xml
> 
> But the output log file is not generated if we have a file already. It is giving the below message which was not the case earlier. `[WSC][DataLoaderRunner.main:104]Log file already exists, appending to status/sfdcSoapTrace.log`

Great - Did that work after installing the libraries?

**Comment by pa1codehub** [comment]
> > Hi @mhamzas , it is working and able to download the data from Salesforce after updating the process.sh with the following command `java -jar dataloader-54.0.0-uber.jar run.mode=batch salesforce.config.dir=$CONF_DIR process.name=$PROCESS > /apps/sdl/data/"$1".OutPut."$now".log`
> > and updated `singleton="false"` to `scope="singleton"` in process-conf.xml
> > But the output log file is not generated if we have a file already. It is giving the below message which was not the case earlier. `[WSC][DataLoaderRunner.main:104]Log file already exists, appending to status/sfdcSoapTrace.log`
> 
> Great - Did that work after installing the libraries?

Nope. I didn't install any additional libraries.

**Comment by mhamzas** [comment]
> Hi @mhamzas, Also, we are not using any log-conf.xml in the code right? Because I do not see any log configuration files in the project.

The logs should be getting added to the same file. you can also try assigning the log file for each of your method under `process-conf.xml` under `map`.

`<entry key="sfdc.debugMessages" value="true"/>
<entry key="sfdc.debugMessagesFile" value="../status/accountMasterSoapTrace.log"/>
`

**Comment by pa1codehub** [comment]
> 

In that case then no need to use the `/apps/sdl/data/"$1".OutPut."$now".log` that we are using currently in the process.sh

**Comment by pa1codehub** [comment]
> [WSC][DataLoaderRunner.main:104]Log file already exists

It is giving the same error
`[WSC][DataLoaderRunner.main:104]Log file already exists`

**Comment by mhamzas** [comment]
> 

You need to change the path of the logfile for each entry

**Comment by mhamzas** [comment]
@pa1codehub Have a look at this https://metamorphant.de/blog/posts/2020-02-28-salesforce-dataloader-graphical-frontend-linux/

Whilst, I am working on it.

**Comment by pa1codehub** [comment]
@mhamzas issue got resolved after adding the log-conf.xml to confg/ directory from [https://github.com/forcedotcom/dataloader/blob/master/release/configs/log-conf.xml](https://github.com/forcedotcom/dataloader/blob/master/release/configs/log-conf.xml)
